//go:build windows

package agentnode

import (
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"syscall"
	"time"
)

const createNewProcessGroup = 0x00000200

func configureRuntimeProcess(cmd *exec.Cmd) {
	cmd.SysProcAttr = &syscall.SysProcAttr{CreationFlags: createNewProcessGroup}
	cmd.Cancel = func() error {
		if cmd.Process == nil {
			return os.ErrProcessDone
		}
		killer := exec.Command("taskkill", "/PID", strconv.Itoa(cmd.Process.Pid), "/T", "/F") // #nosec G204 -- PID is generated by os.Process.
		if err := killer.Run(); err != nil {
			if killErr := cmd.Process.Kill(); killErr != nil {
				return fmt.Errorf("terminate process tree: %w", err)
			}
		}
		return nil
	}
	cmd.WaitDelay = 2 * time.Second
}
